GRANT USAGE ON *.* TO 'godutchtrip'@'localhost';
DROP USER godutchtrip@localhost;

DROP DATABASE IF EXISTS godutchtrip;

CREATE DATABASE godutchtrip DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

CREATE USER godutchtrip@localhost IDENTIFIED BY 'hGMyVZSC5xdTSQy8';
GRANT USAGE ON * . * TO godutchtrip@localhost IDENTIFIED BY 'hGMyVZSC5xdTSQy8' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT ALL PRIVILEGES ON godutchtrip . * TO godutchtrip@localhost;