SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE godutchtrip.person (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  FIRST_NAME varchar(80) DEFAULT NULL,
  LAST_NAME varchar(80) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE godutchtrip.role (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(150) DEFAULT NULL,
  `NAME` varchar(30) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE godutchtrip.`user` (
  `PASSWORD` varchar(50) NOT NULL,
  USER_NAME varchar(20) NOT NULL,
  id bigint(20) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY USER_NAME (USER_NAME),
  KEY FK27E3CBB4CD2494 (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE godutchtrip.user_role (
  USER_ID bigint(20) NOT NULL,
  ROLE_ID bigint(20) NOT NULL,
  UNIQUE KEY USER_ID (USER_ID,ROLE_ID),
  KEY FKBC16F46AAB14F784 (ROLE_ID),
  KEY FKBC16F46A503FBB64 (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE godutchtrip.`user`
  ADD CONSTRAINT FK27E3CBB4CD2494 FOREIGN KEY (id) REFERENCES person (id);

ALTER TABLE godutchtrip.`user_role`
  ADD CONSTRAINT FKBC16F46A503FBB64 FOREIGN KEY (USER_ID) REFERENCES `user` (id),
  ADD CONSTRAINT FKBC16F46AAB14F784 FOREIGN KEY (ROLE_ID) REFERENCES role (id);
